# -*- coding: utf-8 -*-
"""Data Analysis Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1McGrlB3biw73Ftin2VhZ472O5IyQPYEc

**Problem Statement:Analyzing Trends and Patterns in Mobile Phone Sales of Various Brands on Flipkart**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Read the Flipkart mobiles dataset"""

df=pd.read_csv('Flipkart_Mobiles.csv')

df

df.head()

df.shape

"""Data Cleaning

* isnull() is uesd to count number of null values from each column
"""

df.isnull().sum()

df.describe()

"""dropna() is used to remove null values"""

df=df.dropna()
df

df.isnull().sum()

"""To return the number of Mobile brands"""

df['Brand'].value_counts()

df['Color'].value_counts()

df['Storage'].value_counts()

"""To get the information about dataset"""

df.info()

"""To Print the highest selling Price Record"""

df[df['Selling Price']==df['Selling Price'].max()]

"""To Print the Lowest Price Record"""

df[df['Selling Price']==df['Selling Price'].min()]

"""Data Analysis

Different Price range segments for mobiles in Flipkart
"""

# using Bar plot we can represent on graphs
plt.barh(df['Brand'],df['Selling Price'],label='Brand',edgecolor='black',color='red')
plt.ylabel('Brand')
plt.xlabel('Selling price')
plt.legend()
plt.title('Different Price Range Segments for mobiles in Flipkart')
plt.show()

sns.barplot(x='Selling Price', y="Brand", data=df)

#sns.set_style("white")

sns.pairplot(df, hue='Brand')

#brandwise mobile phone price segments
sns.displot(df, x='Selling Price',bins=5, hue='Brand',aspect=1.2)

fig, ax = plt.subplots(figsize=(15,6))
ax = sns.boxplot(x="Brand", y="Selling Price", data=df)

fig,ax=plt.subplots(figsize=(15,6))
ax=sns.boxplot(x="Brand", y="Original Price", data=df)

# correlation between two variables
df.corr()

sns.heatmap(df.corr(),annot=True,cmap='Blues')

sns.catplot(y='Brand',x='Rating',data=df,kind='violin')

# Range of Memory to all brands

memory=df['Memory'].value_counts()
plt.figure(figsize=(8,6))
plt.pie(memory,labels=memory.index,autopct='%1.1f%%',shadow=False)
plt.title('Range of Memory to all brands')
plt.tight_layout()
plt.show()

sns.displot(df, x='Original Price',bins=[5000,10000,15000,20000,25000,30000,35000,40000,50000,60000,80000], aspect=1.5,color='pink')

"""It is quite clear that the market is saturated with lower to mid range cost phones i.e. <25000 INR"""